apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerbos
  namespace: sandbox
  labels:
    app: cerbos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cerbos
  template:
    metadata:
      labels:
        app: cerbos
    spec:
      containers:
        - name: cerbos
          image: ghcr.io/cerbos/cerbos:latest
          args:
            - "server"
            - "--config=/config/cerbos-config.yaml"
          ports:
            - containerPort: 3592
              name: http
            - containerPort: 3593
              name: grpc
          volumeMounts:
            - name: config
              mountPath: /config
            - name: policies
              mountPath: /policies
          livenessProbe:
            httpGet:
              path: /_cerbos/health
              port: 3592
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_cerbos/health
              port: 3592
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: cerbos-config
        - name: policies
          configMap:
            name: cerbos-policies
---
apiVersion: v1
kind: Service
metadata:
  name: cerbos-service
  namespace: sandbox
spec:
  selector:
    app: cerbos
  ports:
    - name: http
      protocol: TCP
      port: 3592
      targetPort: 3592
    - name: grpc
      protocol: TCP
      port: 3593
      targetPort: 3593
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cerbos-config
  namespace: sandbox
data:
  cerbos-config.yaml: |
    server:
      httpListenAddr: ":3592"
      grpcListenAddr: ":3593"
    storage:
      driver: "disk"
      disk:
        directory: "/policies"
        watchForChanges: false
    audit:
      enabled: true
      accessLogsEnabled: true
      decisionLogsEnabled: true
      backend: file
      file:
        path: stdout

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cerbos-policies
  namespace: sandbox
data:
  resource_policy.yaml: |
    ---
    apiVersion: api.cerbos.dev/v1
    resourcePolicy:
      version: "default"
      resource: "resource"
      rules:
        # Allow all operations for backend services from any trust domain
        - actions: ['read', 'create', 'delete']
          effect: EFFECT_ALLOW
          roles:
            - api
          condition:
            match:
              all:
                of:
                  - expr: spiffeMatchTrustDomain(spiffeTrustDomain("spiffe://demo.cerbos.io")).matchesID(spiffeID(P.id))
                  - expr: spiffeID(P.id).path().contains("/ns/sandbox")
