apiVersion: v1
kind: ServiceAccount
metadata:
  name: spiffe-demo-app
  namespace: sandbox
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spiffe-demo-backend
  namespace: sandbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-app
  namespace: sandbox
rules:
  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-app
  namespace: sandbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: example-app
subjects:
  - kind: ServiceAccount
    name: spiffe-demo-app
    namespace: sandbox
  - kind: ServiceAccount
    name: spiffe-demo-backend
    namespace: sandbox
